spring:
  application:
    name: error-report-system

  datasource:
    url: jdbc:postgresql://localhost:5432/error_report_system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  tomcat:
    max-swallow-size: -1
  port: 8080